# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김재령
title: Backend Developer
email: wofud0321@naver.com
github: www.github.com/jae-ryeong

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jae-ryeong

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    안녕하세요! Java, Spring Framework, Spring Boot를 주로 사용하는 웹/앱 서비스 백엔드 개발자 김재령입니다.

    다양한 프로젝트를 진행하며 객체지향적인 설계와 유지보수성을 고려하여 개발을 하기위해 노력하고 있습니다.
    각 프로젝트에 항상 새로운 기술을 학습하고 적용하는 것을 즐기며, 문제 해결을 위한 끊임없는 도전을 이어가고 있으며,
    사용자의 입장에서 생각하며 클라이언트 친화적인 개발을 진행하고자 노력하고 있습니다.

    또한 백엔드 개발 뿐만 아니라 React를 활용한 프론트엔드 경험도 보유하고 있기에 다른 팀과도 원활한 협업이 가능할것이라고 생각합니다.

    매일의 노력이 큰 변화를 만든다고 생각합니다. 
    다소 느리더라도 꾸준히 성장하는 그런 개발자가 되겠습니다.
    감사합니다.
  
  
    <strong>기술 스택<strong>
      - 프레임워크 - <mark>Spring Boot 2/3</mark>
      - 언어 - <mark>Java</mark>, <mark>Kotlin</mark>
      - 테스트 - <mark>Junit</mark>
      - DB(Hibernate) - <mark>MySQL</mark>, <mark>JPA</mark>, <mark>Redis</mark>
      - 기타 - <mark>GCP</mark>, <mark>Docker</mark>, <mark>GitHub</mark>

content:
  - title: Company # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 넥스젠아이티
        sub_title: 스마트/RPA
        caption: 2024.04 ~ 2025.01
        description: | # this will include new lines to allow paragraphs
          <strong>주요 업무</strong>
          - 공공기관 스마트폰 어플 관리 및 유지보수
          - 모바일용 웹 페이지 유지보수
          - RPA 개발 및 유지보수

  - title: Portfolio # Title for the section
    layout: list # Type of content section (list/text)
    content:
      #- layout: left
      - title: Online Store
        link: https://github.com/jae-ryeong/online-store
        sub_title: 2023.12 ~ 진행중
        caption: 1인 풀스택 개발
        description: | # this will include new lines to allow paragraphs
          - 프론트엔드부터 백엔드까지 전 과정을 직접 설계 및 구현
          - MariaDB와 Redis를 활용하여 관계형 데이터와 캐시 데이터를 분리하여 최적화된 데이터베이스 아키텍처를 구축.
          - 포트원(구 아임포트) 외부 API를 연동하여 결제 시스템을 구현, 결제 승인 및 검증 프로세스를 구현
          - 이미지를 클라우드 서버에 업로드 후 URL을 DB에 저장하여 효율적인 데이터 관리
          - 커스텀 예외를 정의하고, 글로벌 예외 처리 로직을 구현하여 예외를 한 눈에 파악할 수 있도록 구현
          - 기술 스택
            - <mark>Spring Boot</mark>, <mark>React</mark>, <mark>TypeScript</mark>, <mark>Docker</mark>, <mark>Docker-Compose</mark>, <mark>JPA</mark>, <mark>MariaDB</mark>, <mark>Redis</mark>, <mark>GCP</mark>

      - title: 약국 검색
        link: https://github.com/jae-ryeong/kakaopharmacy
        sub_title: 2023.12 ~ 2024.01
        caption: 1인 풀스택 개발
        description: | # this will include new lines to allow paragraphs
          - 프론트엔드부터 백엔드까지 전 과정을 직접 설계 및 구현
          - kakao OpenAPI를 활용하여 약국 검색 서비스를 구현
          - Redis 캐싱을 활용해 약국 데이터를 빠르게 조회하여 성능 최적화
          - haversine formula 공식을 적용하여 사용자에게 가장 가까운 약국 추천
          - 약국의 로드뷰 바로가기 기능 제공
          - 기술 스택
            - <mark>Spring Boot</mark>, <mark>Thymeleaf</mark>, <mark>Docker</mark>, <mark>JPA</mark>, <mark>MariaDB</mark>, <mark>Redis</mark>

          

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
