# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김재령
title: Backend Developer
email: wofud0321@naver.com
github: www.github.com/jae-ryeong

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  jae-ryeong

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    안녕하세요! 웹/앱 서비스 백엔드 개발자 김재령입니다. 저는 소프트웨어학과를 전공하며 4년간 웹 개발 관련 지식을 쌓았고, 이를 바탕으로 Spring Boot를 활용한 백엔드 개발에 주력하고 있습니다.

    Google Cloud Storage(GCS)를 활용하여 대용량 이미지 저장 및 관리 시스템의 구축 경험과 Redis를 활용한 캐싱 시스템 구축, Redisson을 이용한 분산 락(Distributed Lock) 구현 등 시스템의 안정성과 성능을 높이기 위해 노력했습니다.

    또한 AWS 환경에서 Docker를 활용하여 프론트엔드(React)와 백엔드(Spring Boot) 서비스를 직접 배포한 경험이 있으며, React 개발 경험은 프론트엔드의 동작 방식과 요구사항에 대한 이해를 높여주었고, 백엔드-프론트엔드 간의 효율적인 API 설계 및 원활한 협업을 이룰 수 있는 기반이 되어주었습니다.
  
  
    <strong>기술 스택<strong>
      - 프레임워크 - <mark>Spring Boot 2/3</mark>
      - 언어 - <mark>Java</mark>, <mark>Kotlin</mark>
      - 테스트 - <mark>Junit</mark>
      - DB(Hibernate) - <mark>MySQL</mark>, <mark>JPA</mark>, <mark>Redis</mark>
      - 기타 - <mark>GCP</mark>, <mark>MariaDB</mark>, <mark>Docker</mark>, <mark>GitHub</mark>

content:
  - title: Company # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 넥스젠아이티
        sub_title: 스마트/RPA
        caption: 2024.04 ~ 2025.01
        description: | # this will include new lines to allow paragraphs
          <strong>주요 업무</strong>
          - 공공기관 스마트폰 어플 관리 및 유지보수
          - 모바일용 웹 페이지 유지보수
          - RPA 개발 및 유지보수

  - title: Portfolio # Title for the section
    layout: list # Type of content section (list/text)
    content:
      #- layout: left
      - title: Movie Recommendation
        link: https://github.com/jae-ryeong/movie-recommend
        sub_title: 2025.04 ~ 진행중
        caption: 1인 백엔드 개발
        description: | # this will include new lines to allow paragraphs
          - Spring Batch를 활용하여 사용자 추천 결과를 병렬 처리 및 페이징 방식으로 일괄 계산, Elasticsearch에 일괄 색인하여 대량 데이터 처리 성능 개선
          - Kafka를 활용해 사용자 행동 이벤트를 비동기로 수집, MySQL에 저장하여 추천 시스템 학습 기반 구축
          - 사용자 평점 데이터를 기반으로 협업 필터링 알고리즘을 구현, 콘텐츠 기반 추천과 결합한 하이브리드 추천 시스템 개발
          - 비동기 처리, 메모리 캐싱, Bulk 방식을 통해 추천 인덱싱 속도 최적화 및 중복 DB 접근 최소화 (기존 5분 -> 20초 단축)
          - 기술 스택
            - <mark>Spring Boot</mark>, <mark>Docker</mark>, <mark>Docker-Compose</mark>, <mark>JPA</mark>, <mark>MySQL</mark>, <mark>Kafka</mark>, <mark>ElasticSearch</mark>


      - title: Online Store
        link: https://github.com/jae-ryeong/online-store
        sub_title: 2023.12 ~ 진행중
        caption: 1인 풀스택 개발
        description: | # this will include new lines to allow paragraphs
          - 프론트엔드부터 백엔드까지 전 과정을 직접 설계 및 구현
          - MariaDB와 Redis를 활용하여 관계형 데이터와 캐시 데이터를 분리하여 최적화된 데이터베이스 아키텍처를 구축.
          - 멀티 스레드 환경에서  Redis 기반 Redisson 분산 락을 활용해 동시성 이슈 해결 및 TTL 설정으로 데드락 방지를 구현
          - 포트원(구 아임포트) 외부 API를 연동하여 결제 시스템을 구현, 결제 승인 및 검증 프로세스를 구현
          - 이미지를 클라우드 서버에 업로드 후 URL을 DB에 저장하여 효율적인 데이터 관리
          - 커스텀 예외를 정의하고, 글로벌 예외 처리 로직을 구현하여 예외를 한 눈에 파악할 수 있도록 구현
          - 기술 스택
            - <mark>Spring Boot</mark>, <mark>React</mark>, <mark>TypeScript</mark>, <mark>Docker</mark>, <mark>Docker-Compose</mark>, <mark>JPA</mark>, <mark>MariaDB</mark>, <mark>Redis</mark>, <mark>GCP</mark>

      - title: Pharmacy Search
        link: https://github.com/jae-ryeong/search-pharmacy
        sub_title: 2023.12 ~ 2024.01
        caption: 1인 풀스택 개발
        description: | # this will include new lines to allow paragraphs
          - 프론트엔드부터 백엔드까지 전 과정을 직접 설계 및 구현
          - kakao OpenAPI를 활용하여 약국 검색 서비스를 구현
          - 한번 검색된 약국 데이터는 Redis에 저장함으로서 중복 검색시 속도 개선
            - LCP(Largest Contentful Paint) 기준 76% (약 4.17배) 성능 향상          
          - haversine formula 공식을 적용하여 사용자에게 가장 가까운 약국 추천
          - 약국의 로드뷰 바로가기 기능 제공
          - 기술 스택
            - <mark>Spring Boot</mark>, <mark>Thymeleaf</mark>, <mark>Docker</mark>, <mark>JPA</mark>, <mark>Redis</mark>

          

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
